### ISSUE TITLE
lolcode licensing

### ISSUE THREAD

**Issue by JoeyCluett** [justinmeza/lolcode-spec#4]
So I understand that the lolcode interpreter(s) you created are open source. Is the specification itself open source as well? I ask because I recently started work on my own LOLCODE interpreter as an academic exercise and would like to put my code on my own GitHub account under GPLv3. Do i need written permission from you to do so? Obviously, you would be credited with the creation of the LOLCODE spec.

**Comment by strugee** [comment]
Why did you close this issue?
